// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTx_wyfZ7T-Swuweuti0b-KguU8w5E8-A',
    appId: '1:427557603199:web:e8c4eeb49c5c594c3bbc4a',
    messagingSenderId: '427557603199',
    projectId: 'womens-wellness-app',
    authDomain: 'womens-wellness-app.firebaseapp.com',
    storageBucket: 'womens-wellness-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa8ZsrdXnT9naZ4bhjzjMB_QQftOXfjbA',
    appId: '1:427557603199:android:1f06f4e53f5225e63bbc4a',
    messagingSenderId: '427557603199',
    projectId: 'womens-wellness-app',
    storageBucket: 'womens-wellness-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnSzxNnRDoWFxtfDeB1oavjct6XbZsag',
    appId: '1:427557603199:ios:a736c69989eac4f13bbc4a',
    messagingSenderId: '427557603199',
    projectId: 'womens-wellness-app',
    storageBucket: 'womens-wellness-app.appspot.com',
    androidClientId: '427557603199-90c9o8g9cardie7uge1opkdgoeb1e2g7.apps.googleusercontent.com',
    iosClientId: '427557603199-gr8i8pec509n91tu6ga0479m34p1hato.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );
}
